@extends('layouts.app')

@section('style')
    <link rel="stylesheet" href="{{ asset('vendor/revslider/css/settings.css') }}">
    <style>.rev-brk-social{box-shadow:none !important}.magazine-big-font{background-image:url(img/demo_magazine/420x200_1.jpg);font-size: 256px;line-height: 200px;color:rgba(var(--brand-primary-rgb), .82);}@media (max-width: 575px){.magazine-big-font{font-size: 150px;}}</style>
@endsection

@section('content')
    <div class="wrapper" style="margin-top:72px;">
        <div id="rev_slider_48_1_wrapper" dir="ltr" class="rev_slider_wrapper fullwidthbanner-container" data-alias="demo_magazine" data-source="gallery" style="margin:0px auto;background:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">
            <div id="rev_slider_48_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.4.8.1">
                <ul>
                    <li data-index="rs-191" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="img/demo_magazine/revslider_img/100x50_3890e-1290x1080_1.jpg" data-rotate="0" data-saveperformance="off" data-title="Slide #1" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                        <img src="img/demo_magazine/revslider_img/3890e-1290x1080_1.jpg" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="5" class="rev-slidebg" data-no-retina>
                        <div class="tp-caption rev_group" id="slide-191-layer-10" data-x="['right','right','right','right']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['0','0','0','0']" data-width="384" data-height="320" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="group" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":10,"speed":1000,"frame":"0","from":"x:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; min-width: 384px; max-width: 384px; max-width: 320px; max-width: 320px; white-space: nowrap; font-size: 20px; line-height: 22px; font-weight: 400; color: #ffffff; letter-spacing: 0px;">
                            <div class="tp-caption tp-shape tp-shapewrapper" id="slide-191-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="384" data-height="319" data-whitespace="nowrap" data-type="shape" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7;background-color:rgba(255,255,255,0);border-color:rgba(255,255,255,0.16);border-style:solid;border-width:0px 0px 1px 1px;"> </div>
                            <div class="tp-caption" id="slide-191-layer-3" data-x="['left','left','left','left']" data-hoffset="['40','40','40','40']" data-y="['top','top','top','top']" data-voffset="['50','50','50','50']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[14,14,14,14]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[14,14,14,14]" style="z-index: 8; white-space: nowrap; font-size: 14px; line-height: 22px; font-weight: 700; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;background-color:rgb(208,160,94);border-radius:12px 12px 12px 12px;">Men’s News </div>
                            <div class="tp-caption" id="slide-191-layer-4" data-x="['left','left','left','left']" data-hoffset="['40','40','40','40']" data-y="['top','top','top','top']" data-voffset="['100','100','100','100']" data-width="305" data-height="57" data-whitespace="normal" data-type="text" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9; min-width: 305px; max-width: 305px; max-width: 57px; max-width: 57px; white-space: normal; font-size: 24px; line-height: 28px; font-weight: 700; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;">Finding inspiration for writing </div>
                            <div class="tp-caption tp-resizeme" id="slide-191-layer-5" data-x="['left','left','left','left']" data-hoffset="['40','40','40','40']" data-y="['top','top','top','top']" data-voffset="['169','169','169','169']" data-width="269" data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 10; min-width: 269px; max-width: 269px; white-space: normal; font-size: 18px; line-height: 24px; font-weight: 400; color: rgba(255,255,255,0.5); letter-spacing: 0px;font-family:Playfair Display;">Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae </div>
                            <div class="tp-caption tp-resizeme" id="slide-191-layer-7" data-x="['left','left','left','left']" data-hoffset="['40','40','40','40']" data-y="['top','top','top','top']" data-voffset="['262','262','262','262']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 11; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: #ffffff; letter-spacing: 0px;font-family:Open Sans;"><i class="fa-icon-clock-o"></i> </div>
                            <div class="tp-caption tp-resizeme" id="slide-191-layer-6" data-x="['left','left','left','left']" data-hoffset="['63','63','63','63']" data-y="['top','top','top','top']" data-voffset="['262','262','262','262']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 12; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 700; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;">11 minutes ago </div>
                        </div>
                        <div class="tp-caption rev_group" id="slide-191-layer-12" data-x="['right','right','right','right']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['320','320','320','320']" data-width="384" data-height="320" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="group" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":800,"speed":1000,"frame":"0","from":"x:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 13; min-width: 384px; max-width: 384px; max-width: 320px; max-width: 320px; white-space: nowrap; font-size: 20px; line-height: 22px; font-weight: 400; color: #ffffff; letter-spacing: 0px;">
                            <div class="tp-caption tp-shape tp-shapewrapper" id="slide-191-layer-13" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="384" data-height="320" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 14;background-color:rgba(255,255,255,0);">
                                <div class="tp-element-background" style="background: url('img/demo_magazine/revslider_img/ddad8-384x320_1.jpg') no-repeat center center; background-size: cover; opacity: 1;"></div>
                            </div>
                            <div class="tp-caption tp-shape tp-shapewrapper" id="slide-191-layer-19" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="384" data-height="320" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 15;background-color:rgba(255,255,255,0.9);"> </div>
                            <div class="tp-caption" id="slide-191-layer-14" data-x="['left','left','left','left']" data-hoffset="['40','40','40','40']" data-y="['top','top','top','top']" data-voffset="['50','50','50','50']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[14,14,14,14]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[14,14,14,14]" style="z-index: 16; white-space: nowrap; font-size: 14px; line-height: 22px; font-weight: 700; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;background-color:rgb(208,160,94);border-radius:12px 12px 12px 12px;">Men’s News </div>
                            <div class="tp-caption" id="slide-191-layer-15" data-x="['left','left','left','left']" data-hoffset="['40','40','40','40']" data-y="['top','top','top','top']" data-voffset="['100','100','100','100']" data-width="305" data-height="57" data-whitespace="normal" data-type="text" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 17; min-width: 305px; max-width: 305px; max-width: 57px; max-width: 57px; white-space: normal; font-size: 24px; line-height: 28px; font-weight: 700; color: #2b2c2d; letter-spacing: 0px;font-family:Montserrat;">Finding inspiration for writing </div>
                            <div class="tp-caption tp-resizeme" id="slide-191-layer-16" data-x="['left','left','left','left']" data-hoffset="['40','40','40','40']" data-y="['top','top','top','top']" data-voffset="['169','169','169','169']" data-width="269" data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 18; min-width: 269px; max-width: 269px; white-space: normal; font-size: 18px; line-height: 24px; font-weight: 400; color: rgba(43,44,45,0.5); letter-spacing: 0px;font-family:Playfair Display;">Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae </div>
                            <div class="tp-caption tp-resizeme" id="slide-191-layer-17" data-x="['left','left','left','left']" data-hoffset="['63','63','63','63']" data-y="['top','top','top','top']" data-voffset="['262','262','262','262']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 19; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 700; color: #2b2c2d; letter-spacing: 0px;font-family:Montserrat;">11 minutes ago </div>
                            <div class="tp-caption tp-resizeme" id="slide-191-layer-18" data-x="['left','left','left','left']" data-hoffset="['40','40','40','40']" data-y="['top','top','top','top']" data-voffset="['262','262','262','262']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 20; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: #2b2c2d; letter-spacing: 0px;font-family:Open Sans;"><i class="fa-icon-clock-o"></i> </div>
                        </div>
                        <div class="tp-caption rev_group" id="slide-191-layer-21" data-x="['right','right','right','right']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['640','640','640','640']" data-width="384" data-height="320" data-whitespace="nowrap" data-visibility="['on','off','off','off']" data-type="group" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":1600,"speed":1000,"frame":"0","from":"x:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 21; min-width: 384px; max-width: 384px; max-width: 320px; max-width: 320px; white-space: nowrap; font-size: 20px; line-height: 22px; font-weight: 400; color: #ffffff; letter-spacing: 0px;">
                            <div class="tp-caption tp-shape tp-shapewrapper" id="slide-191-layer-22" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="384" data-height="320" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 22;background-color:rgba(255,255,255,0);">
                                <div class="tp-element-background" style="background: url('img/demo_magazine/revslider_img/72622-384x320_2.jpg') no-repeat center center; background-size: cover; opacity: 1;"></div>
                            </div>
                            <div class="tp-caption tp-shape tp-shapewrapper" id="slide-191-layer-23" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="384" data-height="320" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 23;background-color:rgba(208,160,94,0.9);"> </div>
                            <div class="tp-caption" id="slide-191-layer-24" data-x="['left','left','left','left']" data-hoffset="['40','40','40','40']" data-y="['top','top','top','top']" data-voffset="['50','50','50','50']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[14,14,14,14]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[14,14,14,14]" style="z-index: 24; white-space: nowrap; font-size: 14px; line-height: 22px; font-weight: 700; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;background-color:rgb(0,0,0);border-radius:12px 12px 12px 12px;">Men’s News </div>
                            <div class="tp-caption" id="slide-191-layer-25" data-x="['left','left','left','left']" data-hoffset="['40','40','40','40']" data-y="['top','top','top','top']" data-voffset="['100','100','100','100']" data-width="305" data-height="57" data-whitespace="normal" data-type="text" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 25; min-width: 305px; max-width: 305px; max-width: 57px; max-width: 57px; white-space: normal; font-size: 24px; line-height: 28px; font-weight: 700; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;">Finding inspiration for writing </div>
                            <div class="tp-caption tp-resizeme" id="slide-191-layer-26" data-x="['left','left','left','left']" data-hoffset="['40','40','40','40']" data-y="['top','top','top','top']" data-voffset="['169','169','169','169']" data-width="269" data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 26; min-width: 269px; max-width: 269px; white-space: normal; font-size: 18px; line-height: 24px; font-weight: 400; color: rgba(255,255,255,0.5); letter-spacing: 0px;font-family:Playfair Display;">Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae </div>
                            <div class="tp-caption tp-resizeme" id="slide-191-layer-27" data-x="['left','left','left','left']" data-hoffset="['63','63','63','63']" data-y="['top','top','top','top']" data-voffset="['262','262','262','262']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 27; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 700; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;">11 minutes ago </div>
                            <div class="tp-caption tp-resizeme" id="slide-191-layer-28" data-x="['left','left','left','left']" data-hoffset="['40','40','40','40']" data-y="['top','top','top','top']" data-voffset="['263','263','263','263']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 28; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: #ffffff; letter-spacing: 0px;font-family:Open Sans;"><i class="fa-icon-clock-o"></i> </div>
                        </div>
                        <div class="tp-caption rev_group rs-parallaxlevel-6" id="slide-191-layer-30" data-x="['left','left','center','center']" data-hoffset="['178','80','0','0']" data-y="['bottom','bottom','top','top']" data-voffset="['200','100','150','150']" data-width="['655','465','655','556']" data-height="['249','248','249','247']" data-whitespace="nowrap" data-type="group" data-basealign="slide" data-responsive_offset="on" data-frames='[{"delay":10,"speed":1800,"frame":"0","from":"x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 29; min-width: 655px; max-width: 655px; max-width: 249px; max-width: 249px; white-space: nowrap; font-size: 20px; line-height: 22px; font-weight: 400; color: #ffffff; letter-spacing: 0px;">
                            <div class="tp-caption" id="slide-191-layer-29" data-x="['left','left','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['0','0','0','0']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[14,14,14,14]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[14,14,14,14]" style="z-index: 30; white-space: nowrap; font-size: 14px; line-height: 22px; font-weight: 700; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;background-color:rgb(208,160,94);border-radius:12px 12px 12px 12px;">Men’s News </div>
                            <div class="tp-caption tp-resizeme" id="slide-191-layer-31" data-x="['left','left','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['46','46','46','46']" data-fontsize="['36','28','36','28']" data-lineheight="['42','34','42','34']" data-width="['577','442','577','500']" data-height="['85','86','85','none']" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 31; min-width: 577px; max-width: 577px; max-width: 85px; max-width: 85px; white-space: normal; font-size: 36px; line-height: 42px; font-weight: 700; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;">How to find the time to write on twitter </div>
                            <div class="tp-caption" id="slide-191-layer-32" data-x="['left','left','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['139','139','139','126']" data-fontsize="['18','17','18','16']" data-lineheight="['24','22','24','20']" data-width="['503','381','503','500']" data-height="['49','50','49','none']" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 32; min-width: 503px; max-width: 503px; max-width: 49px; max-width: 49px; white-space: normal; font-size: 18px; line-height: 24px; font-weight: 400; color: rgba(255,255,255,0.5); letter-spacing: 0px;font-family:Playfair Display;">Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae </div>
                            <div class="tp-caption tp-resizeme" id="slide-191-layer-33" data-x="['left','left','center','center']" data-hoffset="['0','0','-68','-68']" data-y="['top','top','top','top']" data-voffset="['207','207','207','207']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 33; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 400; color: #ffffff; letter-spacing: 0px;font-family:Open Sans;"><i class="fa-icon-clock-o"></i> </div>
                            <div class="tp-caption tp-resizeme" id="slide-191-layer-34" data-x="['left','left','center','center']" data-hoffset="['23','23','0','0']" data-y="['top','top','top','top']" data-voffset="['207','207','207','207']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 34; white-space: nowrap; font-size: 14px; line-height: 14px; font-weight: 700; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;">11 minutes ago </div>
                        </div>
                        <div class="tp-caption rev_group rs-parallaxlevel-6" id="slide-191-layer-41" data-x="['right','left','center','center']" data-hoffset="['400','80','0','0']" data-y="['bottom','top','middle','middle']" data-voffset="['200','100','70','130']" data-width="193" data-height="100" data-whitespace="nowrap" data-type="group" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":1300,"speed":1400,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 35; min-width: 193px; max-width: 193px; max-width: 100px; max-width: 100px; white-space: nowrap; font-size: 20px; line-height: 22px; font-weight: 400; color: #ffffff; letter-spacing: 0px;">
                            <div class="tp-caption tp-resizeme" id="slide-191-layer-43" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[24,24,24,24]" data-paddingright="[24,24,24,24]" data-paddingbottom="[24,24,24,24]" data-paddingleft="[27,27,27,27]" style="z-index: 36; white-space: nowrap; font-size: 16px; line-height: 16px; font-weight: 400; color: #d0a05e; letter-spacing: 0px;font-family:Open Sans;background-color:rgb(255,255,255);border-radius:40px 40px 40px 40px;"><i class="fa-icon-play"></i> </div>
                            <div class="tp-caption" id="slide-191-layer-44" data-x="['left','left','left','left']" data-hoffset="['79','79','79','79']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 37; white-space: nowrap; font-size: 14px; line-height: 16px; font-weight: 700; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;text-transform:uppercase;">Watch <br> the video </div>
                        </div>
                        <div class="tp-caption rev-brk-brands rev_group" id="slide-191-layer-58" data-x="['left','left','left','left']" data-hoffset="['0','0','1','1']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','-4','-4']" data-width="68" data-height="210" data-whitespace="nowrap" data-visibility="['on','on','on','off']" data-type="group" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 39; min-width: 68px; max-width: 68px; max-width: 210px; max-width: 210px; white-space: nowrap; font-size: 20px; line-height: 22px; font-weight: 400; color: #ffffff; letter-spacing: 0px;">
                            <div class="tp-caption rev-brk-social" id="slide-191-layer-56" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['0','0','0','0']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="text" data-actions="" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(208,160,94);"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[10,10,10,10]" data-paddingright="[10,10,10,10]" data-paddingbottom="[10,10,10,10]" data-paddingleft="[10,10,10,10]" style="z-index: 40; white-space: nowrap; font-size: 13px; line-height: 13px; font-weight: 400; color: rgba(255,255,255,0.2); letter-spacing: 0px;font-family:Open Sans;background-color:rgba(208,160,94,0);border-radius:40px 40px 40px 40px;cursor:pointer;"><i class="fa-icon-twitter"></i> </div>
                            <div class="tp-caption rev-brk-social" id="slide-191-layer-47" data-x="['center','center','left','left']" data-hoffset="['0','0','18','18']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['0','0','0','0']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="text" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(208,160,94);"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[10,10,10,10]" data-paddingright="[10,10,10,10]" data-paddingbottom="[10,10,10,10]" data-paddingleft="[10,10,10,10]" style="z-index: 41; white-space: nowrap; font-size: 13px; line-height: 13px; font-weight: 400; color: rgba(255,255,255,0.2); letter-spacing: 0px;font-family:Open Sans;background-color:rgba(208,160,94,0);border-radius:40px 40px 40px 40px;cursor:pointer;"><i class="fa-icon-vk"></i> </div>
                            <div class="tp-caption rev-brk-social" id="slide-191-layer-54" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','bottom','bottom']" data-voffset="['35','35','141','141']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="text" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(208,160,94);"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[10,10,10,10]" data-paddingright="[10,10,10,10]" data-paddingbottom="[10,10,10,10]" data-paddingleft="[10,10,10,10]" style="z-index: 42; white-space: nowrap; font-size: 13px; line-height: 13px; font-weight: 400; color: rgba(255,255,255,0.2); letter-spacing: 0px;font-family:Open Sans;background-color:rgba(208,160,94,0);border-radius:40px 40px 40px 40px;cursor:pointer;"><i class="fa-icon-instagram"></i> </div>
                            <div class="tp-caption rev-brk-social" id="slide-191-layer-52" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','bottom','bottom']" data-voffset="['70','70','106','106']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="text" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(208,160,94);"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[10,10,10,10]" data-paddingright="[10,10,10,10]" data-paddingbottom="[10,10,10,10]" data-paddingleft="[10,10,10,10]" style="z-index: 43; white-space: nowrap; font-size: 13px; line-height: 13px; font-weight: 400; color: rgba(255,255,255,0.2); letter-spacing: 0px;font-family:Open Sans;background-color:rgba(208,160,94,0);border-radius:40px 40px 40px 40px;cursor:pointer;"><i class="fa-icon-google"></i> </div>
                            <div class="tp-caption rev-brk-social" id="slide-191-layer-50" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','bottom','bottom']" data-voffset="['105','105','70','70']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="text" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(208,160,94);"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[10,10,10,10]" data-paddingright="[10,10,10,10]" data-paddingbottom="[10,10,10,10]" data-paddingleft="[10,10,10,10]" style="z-index: 44; white-space: nowrap; font-size: 13px; line-height: 13px; font-weight: 400; color: rgba(255,255,255,0.2); letter-spacing: 0px;font-family:Open Sans;background-color:rgba(208,160,94,0);border-radius:40px 40px 40px 40px;cursor:pointer;"><i class="fa-icon-youtube"></i> </div>
                            <div class="tp-caption rev-brk-social" id="slide-191-layer-48" data-x="['left','left','center','center']" data-hoffset="['16','16','0','0']" data-y="['top','top','bottom','bottom']" data-voffset="['140','140','35','35']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="text" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":"+0","speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(208,160,94);"}]' data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[10,10,10,10]" data-paddingright="[10,10,10,10]" data-paddingbottom="[10,10,10,10]" data-paddingleft="[10,10,10,10]" style="z-index: 45; white-space: nowrap; font-size: 13px; line-height: 13px; font-weight: 400; color: rgba(255,255,255,0.2); letter-spacing: 0px;font-family:Open Sans;background-color:rgba(208,160,94,0);border-radius:40px 40px 40px 40px;cursor:pointer;"><i class="fa-icon-vimeo"></i> </div>
                        </div>
                        <div class="tp-caption tp-shape tp-shapewrapper" id="slide-191-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="full" data-height="full" data-whitespace="nowrap" data-type="shape" data-basealign="slide" data-responsive_offset="off" data-responsive="off" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5;background-color:rgba(0,0,0,0.7);"> </div>
                        <div class="tp-caption tp-shape tp-shapewrapper" id="slide-191-layer-45" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="68" data-height="full" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="shape" data-basealign="slide" data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 38;background-color:rgb(43,44,45);"> </div>
                    </li>
                </ul>
                <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>
            </div>
        </div>
        <h1 class="sr-only">{{ trans('app.title_main') }}{{ trans('app.title_org') }}</h1>
        <section class="row no-gutters">
            <div class="col-xl-4">
                <div class="blog-grid-card lazyload blog-grid-card_small blog-grid-card_white" data-bg="img/demo_magazine/640x420_1.jpg" data-brk-library="component__blog_grid">
                    <div class="blog-grid-card__before"></div>
                    <div class="blog-grid-card__item text-center">
                        <a href="#" class="blog-grid-card__avatar">
                            <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo_magazine/116x116_6.jpg" alt="alt" class="lazyload">
                        </a>
                        <a href="#" class="blog-grid-card__name font__family-montserrat font__weight-bold font__size-14 line__height-16">Nekro Merinstar</a>
                        <a href="#" class="blog-grid-card__title font__family-montserrat font__weight-bold">
                            Stay on budget
                        </a>
                        <div class="blog-grid-card__desc font__family-playfair">Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae</div>
                        <div class="d-flex justify-content-center flex-wrap">
                            <a href="#" class="blog-grid-card__cat font__family-montserrat font__weight-bold font__size-14 line__height-22">Men’s News</a>
                            <div class="blog-grid-card__time font__family-montserrat font__weight-bold font__size-14 line__height-22"><i class="far fa-clock"></i> 11 minutes ago</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-4">
                <div class="blog-grid-card lazyload blog-grid-card_small blog-grid-card_dark" data-bg="img/demo_magazine/640x420_2.jpg" data-brk-library="component__blog_grid">
                    <div class="blog-grid-card__before"></div>
                    <div class="blog-grid-card__item text-center">
                        <a href="#" class="blog-grid-card__avatar">
                            <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo_magazine/116x116_7.jpg" alt="alt" class="lazyload">
                        </a>
                        <a href="#" class="blog-grid-card__name font__family-montserrat font__weight-bold font__size-14 line__height-16">Nekro Merinstar</a>
                        <a href="#" class="blog-grid-card__title font__family-montserrat font__weight-bold">
                            Finding inspiration for writing
                        </a>
                        <div class="blog-grid-card__desc font__family-playfair">Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae</div>
                        <div class="d-flex justify-content-center flex-wrap">
                            <a href="#" class="blog-grid-card__cat font__family-montserrat font__weight-bold font__size-14 line__height-22">Men’s News</a>
                            <div class="blog-grid-card__time font__family-montserrat font__weight-bold font__size-14 line__height-22"><i class="far fa-clock"></i> 11 minutes ago</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-4">
                <div class="blog-grid-card lazyload blog-grid-card_small blog-grid-card_white" data-bg="img/demo_magazine/640x420_3.jpg" data-brk-library="component__blog_grid">
                    <div class="blog-grid-card__before"></div>
                    <div class="blog-grid-card__item text-center">
                        <a href="#" class="blog-grid-card__avatar">
                            <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo_magazine/116x116_3.jpg" alt="alt" class="lazyload">
                        </a>
                        <a href="#" class="blog-grid-card__name font__family-montserrat font__weight-bold font__size-14 line__height-16">Nekro Merinstar</a>
                        <a href="#" class="blog-grid-card__title font__family-montserrat font__weight-bold">
                            Wrap up the project
                        </a>
                        <div class="blog-grid-card__desc font__family-playfair">Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae</div>
                        <div class="d-flex justify-content-center flex-wrap">
                            <a href="#" class="blog-grid-card__cat font__family-montserrat font__weight-bold font__size-14 line__height-22">Men’s News</a>
                            <div class="blog-grid-card__time font__family-montserrat font__weight-bold font__size-14 line__height-22"><i class="far fa-clock"></i> 11 minutes ago</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-8">
                <div class="row no-gutters">
                    <div class="col-xl-6">
                        <div class="blog-grid-card lazyload blog-grid-card_small blog-grid-card_dark" data-bg="img/demo_magazine/640x420_2.jpg" data-brk-library="component__blog_grid">
                            <div class="blog-grid-card__before"></div>
                            <div class="blog-grid-card__item text-center">
                                <a href="#" class="blog-grid-card__avatar">
                                    <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo_magazine/116x116_4.jpg" alt="alt" class="lazyload">
                                </a>
                                <a href="#" class="blog-grid-card__name font__family-montserrat font__weight-bold font__size-14 line__height-16">Nekro Merinstar</a>
                                <a href="#" class="blog-grid-card__title font__family-montserrat font__weight-bold">
                                    According to schedule
                                </a>
                                <div class="blog-grid-card__desc font__family-playfair">Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae</div>
                                <div class="d-flex justify-content-center flex-wrap">
                                    <a href="#" class="blog-grid-card__cat font__family-montserrat font__weight-bold font__size-14 line__height-22">Men’s News</a>
                                    <div class="blog-grid-card__time font__family-montserrat font__weight-bold font__size-14 line__height-22"><i class="far fa-clock"></i> 11 minutes ago</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6">
                        <div class="blog-grid-card lazyload blog-grid-card_small blog-grid-card_white" data-bg="img/demo_magazine/640x420_4.jpg" data-brk-library="component__blog_grid">
                            <div class="blog-grid-card__before"></div>
                            <div class="blog-grid-card__item text-center">
                                <a href="#" class="blog-grid-card__avatar">
                                    <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo_magazine/116x116_5.jpg" alt="alt" class="lazyload">
                                </a>
                                <a href="#" class="blog-grid-card__name font__family-montserrat font__weight-bold font__size-14 line__height-16">Nekro Merinstar</a>
                                <a href="#" class="blog-grid-card__title font__family-montserrat font__weight-bold">
                                    Schedule a meeting
                                </a>
                                <div class="blog-grid-card__desc font__family-playfair">Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae</div>
                                <div class="d-flex justify-content-center flex-wrap">
                                    <a href="#" class="blog-grid-card__cat font__family-montserrat font__weight-bold font__size-14 line__height-22">Men’s News</a>
                                    <div class="blog-grid-card__time font__family-montserrat font__weight-bold font__size-14 line__height-22"><i class="far fa-clock"></i> 11 minutes ago</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-12">
                        <div class="blog-grid-card lazyload blog-grid-card_small blog-grid-card_colored" data-bg="img/demo_magazine/1280x420_1.jpg" data-brk-library="component__blog_grid">
                            <div class="blog-grid-card__before"></div>
                            <div class="blog-grid-card__item text-center">
                                <a href="#" class="blog-grid-card__avatar">
                                    <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo_magazine/116x116_3.jpg" alt="alt" class="lazyload">
                                </a>
                                <a href="#" class="blog-grid-card__name font__family-montserrat font__weight-bold font__size-14 line__height-16">Nekro Merinstar</a>
                                <a href="#" class="blog-grid-card__title font__family-montserrat font__weight-bold">
                                    Give the green light
                                </a>
                                <div class="blog-grid-card__desc font__family-playfair">Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae</div>
                                <div class="d-flex justify-content-center flex-wrap">
                                    <a href="#" class="blog-grid-card__cat font__family-montserrat font__weight-bold font__size-14 line__height-22">Men’s News</a>
                                    <div class="blog-grid-card__time font__family-montserrat font__weight-bold font__size-14 line__height-22"><i class="far fa-clock"></i> 11 minutes ago</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-4">
                <div class="blog-grid-card lazyload blog-grid-card_big blog-grid-card_dark" data-bg="img/demo_magazine/640x840_1.jpg" data-brk-library="component__blog_grid">
                    <div class="blog-grid-card__before"></div>
                    <div class="blog-grid-card__item text-center">
                        <a href="#" class="blog-grid-card__avatar">
                            <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo_magazine/116x116_6.jpg" alt="alt" class="lazyload">
                        </a>
                        <a href="#" class="blog-grid-card__name font__family-montserrat font__weight-bold font__size-14 line__height-16">Nekro Merinstar</a>
                        <a href="#" class="blog-grid-card__title font__family-montserrat font__weight-bold">
                            Start from scratch
                        </a>
                        <div class="blog-grid-card__desc font__family-playfair">Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae</div>
                        <div class="d-flex justify-content-center flex-wrap">
                            <a href="#" class="blog-grid-card__cat font__family-montserrat font__weight-bold font__size-14 line__height-22">Men’s News</a>
                            <div class="blog-grid-card__time font__family-montserrat font__weight-bold font__size-14 line__height-22"><i class="far fa-clock"></i> 11 minutes ago</div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="position-relative pt-30 pb-30">
            <div class="brk-layer position-absolute bg-cover bg-norepeat bg-position_bottom-center opacity-20 lazyload" data-bg="img/demo_magazine/1280x120_1.png"></div>
            <div class="container position-relative brk-z-index-10 text-center">
                <div class="row justify-content-center align-items-center">
                    <div class="col-md-auto">
                        <span class="font__weight-bold font__family-montserrat font__size-32 line__height-52 text-dark text-uppercase">View our shop</span>
                        <span class="font__weight-light font__family-montserrat font__size-32 line__height-52 text-dark text-uppercase">& buy our best products</span>
                    </div>
                </div>
            </div>
        </section>
        <section class="brk-base-bg-6 pt-lg-110 pt-40 pb-90">
            <div class="container">
                <div class="row align-items-end brk-gutters-5">
                    <div class="col-lg-auto text-center text-lg-left">
                        <span class="brk-text-clip bg-cover font__weight-bold magazine-big-font">136</span>
                    </div>
                    <div class="col-lg-auto text-center text-lg-left">
                        <div class="font__family-montserrat font__weight-bold font__size-24 line__height-28 mb-20 text-uppercase">
                            <span class="brk-base-font-color">Partners</span><br>
                            <span class="text-white">with us</span>
                        </div>
                    </div>
                </div>
                <div class="row pt-70">
                    <div class="col-lg-3 col-sm-6 pt-15 pb-15"><a href="#" class="logo-set-dark" data-brk-library="component__widgets">
                            <img class="logo-set-dark__img lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo-logo-set.png" alt="alt">
                        </a></div>
                    <div class="col-lg-3 col-sm-6 pt-15 pb-15"><a href="#" class="logo-set-dark" data-brk-library="component__widgets">
                            <img class="logo-set-dark__img lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo-logo-set.png" alt="alt">
                        </a></div>
                    <div class="col-lg-3 col-sm-6 pt-15 pb-15"><a href="#" class="logo-set-dark" data-brk-library="component__widgets">
                            <img class="logo-set-dark__img lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo-logo-set.png" alt="alt">
                        </a></div>
                    <div class="col-lg-3 col-sm-6 pt-15 pb-15"><a href="#" class="logo-set-dark" data-brk-library="component__widgets">
                            <img class="logo-set-dark__img lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo-logo-set.png" alt="alt">
                        </a></div>
                    <div class="col-lg-3 col-sm-6 pt-15 pb-15"><a href="#" class="logo-set-dark" data-brk-library="component__widgets">
                            <img class="logo-set-dark__img lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo-logo-set.png" alt="alt">
                        </a></div>
                    <div class="col-lg-3 col-sm-6 pt-15 pb-15"><a href="#" class="logo-set-dark" data-brk-library="component__widgets">
                            <img class="logo-set-dark__img lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo-logo-set.png" alt="alt">
                        </a></div>
                    <div class="col-lg-3 col-sm-6 pt-15 pb-15"><a href="#" class="logo-set-dark" data-brk-library="component__widgets">
                            <img class="logo-set-dark__img lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo-logo-set.png" alt="alt">
                        </a></div>
                    <div class="col-lg-3 col-sm-6 pt-15 pb-15"><a href="#" class="logo-set-dark" data-brk-library="component__widgets">
                            <img class="logo-set-dark__img lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="img/demo-logo-set.png" alt="alt">
                        </a></div>
                </div>
            </div>
        </section>
    </div>
@endsection

@section('script')
    <script defer="defer" src="{{ asset('vendor/revslider/js/jquery.themepunch.tools.min.js') }}"></script>
    <script defer="defer" src="{{ asset('vendor/revslider/js/jquery.themepunch.revolution.min.js') }}"></script>
    <script defer="defer" src="{{ asset('vendor/revslider/js/extensions/revolution.extension.actions.min.js') }}"></script>
    <script defer="defer" src="{{ asset('vendor/revslider/js/extensions/revolution.extension.layeranimation.min.js') }}"></script>
    <script defer="defer" src="{{ asset('vendor/revslider/js/extensions/revolution.extension.parallax.min.js') }}"></script>
    <script defer="defer" src="{{ asset('vendor/revslider/js/extensions/revolution.extension.slideanims.min.js') }}"></script>
    <script>
        var revapi48,
            tpj;
        (function() {
            if (!/loaded|interactive|complete/.test(document.readyState)) document.addEventListener("DOMContentLoaded", onLoad);
            else onLoad();

            function onLoad() {
                if (tpj === undefined) {
                    tpj = jQuery;
                    if ("off" == "on") tpj.noConflict();
                }
                if (tpj("#rev_slider_48_1").revolution == undefined) {
                    revslider_showDoubleJqueryError("#rev_slider_48_1");
                } else {
                    revapi48 = tpj("#rev_slider_48_1").show().revolution({
                        sliderType: "hero",
                        jsFileLocation: "vendor/revslider/js/",
                        sliderLayout: "fullwidth",
                        dottedOverlay: "none",
                        delay: 6000,
                        navigation: {},
                        responsiveLevels: [1240, 1024, 778, 480],
                        visibilityLevels: [1240, 1024, 778, 480],
                        gridwidth: [1200, 992, 768, 576],
                        gridheight: [960, 800, 800, 640],
                        lazyType: "none",
                        scrolleffect: {
                            blur: "on",
                            maxblur: "50",
                            on_parallax_layers: "on",
                        },
                        parallax: {
                            type: "scroll",
                            origo: "slidercenter",
                            speed: 400,
                            speedbg: 0,
                            speedls: 1000,
                            levels: [0, 10, 15, 20, 25, -30, -35, -40, 45, 46, 47, 48, 49, 50, 51, 55],
                        },
                        shadow: 0,
                        spinner: "spinner0",
                        autoHeight: "off",
                        disableProgressBar: "on",
                        hideThumbsOnMobile: "off",
                        hideSliderAtLimit: 0,
                        hideCaptionAtLimit: 0,
                        hideAllCaptionAtLilmit: 0,
                        debugMode: false,
                        fallbacks: {
                            simplifyAll: "off",
                            disableFocusListener: false,
                        }
                    });
                }; /* END OF revapi call */
            }; /* END OF ON LOAD FUNCTION */
        }()); /* END OF WRAPPING FUNCTION */
    </script>
@endsection
